# Generated by Django 3.1 on 2020-09-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('DoB', models.DateTimeField(auto_now_add=True, verbose_name='DoB')),
            ],
        ),
    ]
